### ISSUE TITLE
v1.0.9 with failed block validation and changed front end markup

### ISSUE THREAD

**Issue by ocean90** [DanielFloeter/hyperlink-group-block#11]
Hello there, the latest release v1.0.9, which based on [semver](https://semver.org/) should only be a patch release without breaking changes, has at least two breaking changes:

* The markup in the front end has changed and the `wp-block-hyperlink-group` class does no longer exist. Instead the `wp-block-tiptip-hyperlink-group-block` class is now applied to the anchor tag directly.
* The block validation in the editor is failing thus all existing blocks are marked as broken. Output from the browser console:
```
blocks.min.js?ver=69022aed79bfd45b3b1d:10 Block validation: Block validation failed for `tiptip/hyperlink-group-block` ({name: 'tiptip/hyperlink-group-block', icon: {…}, keywords: Array(7), attributes: {…}, providesContext: {…}, …}).

Content generated by `save` function:

<a class="wp-block-hyperlink-group" href=""><div class="wp-block-tiptip-hyperlink-group-block"></div></a>

Content retrieved from post body:

<a class="wp-block-hyperlink-group" href="https://example.org/de/digital/data-solutions/"><div class="wp-block-tiptip-hyperlink-group-block">





</div></a>
```
* This also causing the existing blocks no longer having a link.

Please take a look at https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/ to provide a proper fallback for existing blocks.

I think for now the 1.0.9 update should be reverted as 1.0.10 which behaves as 1.0.8 and then create a new release (maybe 2.0?) with the new changes and fallbacks so existing blocks don't need to be updated.

**Comment by ocean90** [comment]
@DanielFloeter Any thoughts on these issues?

**Comment by DanielFloeter** [comment]
Please click 'Attempt Block Recovery' or leave it as it is, if you have many blocks and you don't need any changes.
We update the save() and use an PHP render_callback and not react save() anymore. We have no fallback about deprecation versions.
