### ISSUE TITLE
Hyperlink Group Block cannot render on pages without an ID or title

### ISSUE THREAD

**Issue by GeoffDusome** [DanielFloeter/hyperlink-group-block#13]
### The Issue

On line 19 and 26 of `hyperlink-group-block.php`, the PHP render callback function (`render_block_core_post_title`) removes the ability for the Hyperlink Group Block to render on pages that do not have IDs or titles assigned. This means that the Hyperlink Group Block isn't able to render on templates files such as `index.html`, `archive.html` or `404.html`.

### Suggested Fix

Only check for no ID or Title if `$attributes['queryLoopLink']` is `true`.

**Comment by GeoffDusome** [comment]
@DanielFloeter bumping this for visibility. This is breaking functionality in the plugin and we're hoping to get it fixed, please!

**Comment by DanielFloeter** [comment]
@GeoffDusome Can you write which Theme, PHP and WordPress version do you use? Is the issue in the backend, frontend or browser-console?
Because I get no issue. Can you please describe how I can get it?

**Comment by GeoffDusome** [comment]
@DanielFloeter Sure, here's some notes on our environment:
- WordPress 6.2
- Custom theme (doesn't really matter what theme as long as it has a archive, 404, or similar template, templates that don't contain IDs)
- PHP 8.1.10
- Issue only persists on the front end of the website.

Steps to reproduce
- Go to Appearance > Editor
- Click Templates > 404
- Click in the editor window to activate it
- Add a Hyperlink Group Block anywhere on the page
- Save and view the front end of the website. Easiest way to get to a 404 page is to just add a random string of characters to the end of the URL 
- You shouldn't see the Hyperlink Group Block you created because the page on the front end doesn't contain an ID or a title.

Let me know if this helps!
