### ISSUE TITLE
Add WPML support (to translate the content inside href)

### ISSUE THREAD

**Issue by webdev69420** [DanielFloeter/hyperlink-group-block#17]
Hey,

Could you add WPML support so I can translate the link after creating my page using this block?

I'm trying to add this functionnality myself but I'm more of a front-end dev so I'm struggling a bit...

Thanks! :)

**Comment by DanielFloeter** [comment]
How do you use the Block you have to translate the link?
With WPML you get for each language an own page, blog post, etc. where you can set different links on each language page, blog post, etc.

**Comment by DanielFloeter** [comment]
We write sth. to the [Block FAQs](https://wordpress.org/plugins/hyperlink-group-block/#faq):

There are two kinds for WPML translation.

Translate with "WordPress Editor", not with "WPML Translation Editor":
WPML > Settings > Translation Editor > Classic Translation Editor
or
Your site in admin / gutenberg mode > right sidebar / Page > language > Translations > WordPress Editor

Other option but there is a bug, it doesn't work for us?
[wpml.org/faq](https://wpml.org/faq/) / FAQ > How-To > "How can I translate links and HTML attributes in the Advanced Translation Editor?"
Search content: "http" [YouTube](https://wpml.org/announcements/2020/02/translating-links-with-advanced-translation-editor/)
