### ISSUE TITLE
Authenticated (Contributor+) Stored Cross-Site Scripting

### ISSUE THREAD

**Issue by warpcoil** [DanielFloeter/hyperlink-group-block#22]
Hi Daniel

Thank You for your plugin.

I just need to report that the WordFence and PatchStack Team have reported on a vulnerability. It should be noted that authentication is required for this bug to realised.

I see the report on the [WordFence website](https://www.wordfence.com/threat-intel/vulnerabilities/wordpress-plugins/hyperlink-group-block/hyperlink-group-block-1175-authenticated-contributor-stored-cross-site-scripting).

I look forward to the continued support of this plugin (and hopefully WPML support down the road).

Thank You and Kind Regards

Bobby

**Comment by DanielFloeter** [comment]
Thank you for your info. The issue is patched.
