### ISSUE TITLE
This block has encountered an error and cannot be previewed.

### ISSUE THREAD

**Issue by justravis** [DanielFloeter/hyperlink-group-block#4]
Just installed the plugin and it immediately started malfunctioning.
![image](https://user-images.githubusercontent.com/20541739/152443201-d03388f0-14a6-48c2-b02c-fc8eacb0af2a.png)
![image](https://user-images.githubusercontent.com/20541739/152443568-18277acb-d952-42fe-83fa-86563f4ee58d.png)
![image](https://user-images.githubusercontent.com/20541739/152443478-74d5c7aa-a8a7-4a4b-89dd-446379c0d32e.png)

**Comment by justravis** [comment]
@DanielFloeter If I set the link of the group first, I am unable to enter a class in the right sidebar. Setting the color is not working. Is the A tag supposed to be inside the P tag?
![image](https://user-images.githubusercontent.com/20541739/152598449-872e734d-ce92-4c21-be08-b3ba629373c7.png)
http://ridgeline.temp.domains/~ahaf/about/campaign-for-cursive/

**Comment by DanielFloeter** [comment]
`<a>` inside `<p>` is allowed. But not allowed is `<p>` inside `<a>` or  `<a>` inside `<a>`.
