### ISSUE TITLE
Include migration code for change in markup

### ISSUE THREAD

**Issue by grappler** [DanielFloeter/hyperlink-group-block#5]
When updating from `1.0.1` to `1.0.4` I am getting the following error in the block editor.

<img width="316" alt="image" src="https://user-images.githubusercontent.com/1785641/156877517-62f2e5d0-ccd0-489b-b5a6-a2a3f282a7d3.png">

And the following from the browser developer console.
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/1785641/156877623-e4f72f6e-b1bf-4ee5-8645-7ebb08b878bf.png">

The cause for this is https://github.com/DanielFloeter/hyperlink-group-block/commit/c7c63768ee747a18d1329f1b6fbe847a8d8ffe98. I would have preferred a markup change to be included in a higher version change if you are following [semantic versioning](https://semver.org/). I have not checked the styling for this element, but a markup change could break the styling.

The block editor provides a `deprecated` parameter that supports a migration process. This normally solves this issue.

https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/#changing-the-innerblocks

I have a feeling that then the code in `add_button_size_class()` will not be needed.

P.s. If functions like `add_button_size_class()` are not prefixed or do not use a namespace, there is a chance that it will conflict with another plugin or theme and uses the same function name.

**Comment by DanielFloeter** [comment]
There's no harm in using a namespace.

I then use `deprecated` for the next change, if a change cannot be avoided. Thank you for your help

**Comment by grappler** [comment]
Thanks for adding the namespace! 😁 

Would it be possible to include a `deprecated` process for this change too? Then I can update the two sites that are using the plugin.

Happy to help with any questions 😊

**Comment by DanielFloeter** [comment]
Why don't click 'Attempt Block Recovery' and WordPress don't show that info anymore?

I know changes in the rendered Block HTML are to be avoid.
I don't know exactly which versions have HTML changes and how many deprecated flags I need to set for old code. It would have been better if I had always done it immediately
